# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := c2play c2play-x11

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

c2play: 
	@echo "==== Building c2play ($(config)) ===="
	@${MAKE} --no-print-directory -C build/gmake -f c2play.make

c2play-x11: 
	@echo "==== Building c2play-x11 ($(config)) ===="
	@${MAKE} --no-print-directory -C build/gmake -f c2play-x11.make

clean:
	@${MAKE} --no-print-directory -C build/gmake -f c2play.make clean
	@${MAKE} --no-print-directory -C build/gmake -f c2play-x11.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   c2play"
	@echo "   c2play-x11"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
